### PR TITLE
first commit win recipe addition

### PR DESCRIPTION
**Pull request by ngodber**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Compiles using nmake but struggling to verify function. Execution of the reference A.poly does not appear to generate the outputs describe in the help function but also doesnt show any kind of crash so not exactly sure what is going on there.

### CODE REVIEW

**Comment by ngodber** [comment]
First binary conda forge recipe so please be gentle!

**Comment by ngodber** [comment]
@conda-forge-admin, please rerender

**Comment by ngodber** [comment]
@conda-forge-admin, please restart ci

**Comment by ngodber** [comment]
@nehaljwani thanks for the help. I'm not sure what is going on with the osx command. Doesn't seem to be recipe related.

**Comment by nehaljwani** [comment]
I know what's going on, will push a fix in a few mins.

**Pull request merged**
